title: "Momo's Journal"
theme: primer

# Optional: social links
# github_username: your-username
# linkedin_username: your-linkedin
# twitter_username: your-twitter

# Optional: Google Analytics (replace with your tracking ID if needed)
# google_analytics: G-XXXXXXXXXX

# Plugins (minima supports these by default)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
